version: '3.8'

services:
  web:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8083"]
